version: '3.8'
services:
    postgres:
        image: postgres:13.3-alpine
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - '127.0.0.1:5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 6s
            retries: 10
            timeout: 5s
